# 基本配置
title: "开源设计"
description: "hello 开源设计课程"
lang: zh-CN
author: 开源设计团队
url: "https://luckylcy1.github.io/GitHub-Pages"
baseurl: "/GitHub-Pages" # 注意要与 GitHub 项目名一致
github_username: luckylcy1

# 远程主题
remote_theme: pages-themes/architect@v0.2.0

# 插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag # SEO 优化
  - jekyll-sitemap # 自动生成站点地图
  - jekyll-feed # RSS 订阅
  - jekyll-paginate # 分页
  - jekyll-assets # 资源优化
  - jekyll-redirect-from # 页面重定向

# SEO 设置
seo:
  type: "website"
  twitter:
    username: "你的 Twitter 账户"
  social:
    github: luckylcy1
    weibo: "你的微博链接"
    wechat: "你的微信链接"

# 导航栏配置
navbar:
  logo: /assets/images/logo.png # 替换为你的 logo 图片路径
  links:
    - title: "主页"
      url: "/"
    - title: "课程"
      url: "/courses/"
    - title: "关于我们"
      url: "/about/"
    - title: "联系"
      url: "/contact/"

# 分页配置
paginate: 5 # 每页显示 5 篇文章
paginate_path: "/page:num/"

# 自定义样式
theme:
  color_scheme: dark # 颜色方案：dark 或 light
  accent_color: "#ff6600" # 自定义强调色
  font:
    heading: "Noto Sans SC, sans-serif"
    body: "Open Sans, sans-serif"

# 主页设置
home:
  hero_image: /assets/images/hero-bg.jpg # 替换为你的背景图片路径
  hero_title: "欢迎来到开源设计"
  hero_subtitle: "一站式学习开源设计"

# 站点地图配置
sitemap:
  exclude:
    - /404.html

# 扩展内容
collections:
  courses:
    output: true
    permalink: /courses/:name/
